### PR TITLE
make SSR and usage of express flexible

### PR DESCRIPTION
**Pull request by vedmalex**
Hi i've update saturn to have SSR and express-server to more flexibe.

TODO:

- [X] Update HISTORY.md with your change
- [X] Rebase your changes on master so that they can be merged easily

### CODE REVIEW

**Comment by vedmalex** [comment]
It allow to use different render engines and techniques in derived application.

**Comment by tmeasday** [comment]
Hey @vedmalex, apologies for the delay at looking at this, busy week.

Can we split the express bit out into a separate PR? I'm not sure I understand what it's for, let's take the conversation to a different PR.

Regarding the SSR changes:

1. I think the `ourSSR` function should be in a separate import, so people can import it and tweak it themselves. Maybe `app/to-string` ?

2. I'm to sure what your alternate SSR implementation looks like (it might be helpful to post it somewhere), so I'm guessing here, but would it make sense to pass in the `client` and `store` rather than the `createStore/createClient` functions?

3. In fact, the entire `component` variable seems pretty uncontroversial, but maybe not?

**Comment by tmeasday** [comment]
I'm not sure `to-string` is the best name given it's rendering to a response, maybe `server-render` is better?

**Comment by vedmalex** [comment]
Hi! I very glad to see any reaction! thank you.
of course I will separate it inti different pull request.
please see my issue #31 about future of the project.

**Pull request closed without merging**
